import { CalendarDays, Check, Circle, LayoutGrid, List, MessageSquare, MoreHorizontal, Plus } from 'lucide-react'
import { BrandMark } from '@/components/layout/brand'
import { cn } from '@/lib/utils'

const columns = [
  { label: 'Backlog', color: 'bg-status-backlog', tasks: [{ key: 'HL-6', title: 'Write API documentation', initials: 'AV', priority: 'Normal', date: 'Oct 6', comments: 2 }, { key: 'HL-8', title: 'Prepare user testing plan', initials: 'MN', priority: 'High', date: 'Oct 9', comments: 1 }] },
  { label: 'In Progress', color: 'bg-status-progress', tasks: [{ key: 'HL-4', title: 'Build login flow', initials: 'RM', priority: 'Urgent', date: 'Tomorrow', comments: 4 }, { key: 'HL-5', title: 'Create style guide', initials: 'MN', priority: 'Normal', date: 'Oct 3', comments: 2 }] },
  { label: 'Done', color: 'bg-status-done', tasks: [{ key: 'HL-1', title: 'Define project scope', initials: 'AV', priority: 'High', date: 'Complete', comments: 3 }, { key: 'HL-3', title: 'Set up repository', initials: 'RM', priority: 'Normal', date: 'Complete', comments: 1 }] },
]

export function ProductPreview() {
  return <figure aria-label="Illustrative Hostlink board with tasks, assignees and progress" className="overflow-hidden rounded-xl border border-sidebar-foreground/20 bg-surface leading-normal text-body shadow-2xl">
    <div className="flex items-center justify-between border-b px-4 py-3"><div className="flex items-center gap-2"><BrandMark className="size-6" /><span className="text-xs font-semibold text-strong">Your workspace</span></div><div className="flex gap-1.5" aria-hidden="true">{[0, 1, 2].map(i => <span key={i} className="size-1.5 rounded-full bg-border" />)}</div></div>
    <div className="p-4 sm:p-5"><div className="mb-4 flex items-center justify-between gap-2"><div><p className="text-[10px] text-muted-foreground">Projects / Website Revamp</p><h2 className="mt-1 text-base font-semibold">Website Revamp</h2></div><div className="flex -space-x-2" aria-hidden="true">{['AV', 'RM', 'MN'].map((name, i) => <span key={name} className={cn('flex size-7 items-center justify-center rounded-full border-2 border-surface text-[9px] font-medium text-primary-foreground', i === 0 ? 'bg-avatar-teal' : i === 1 ? 'bg-avatar-indigo' : 'bg-avatar-amber')}>{name}</span>)}</div></div>
      <div className="mb-4 flex items-center gap-5 border-b text-[11px]"><span className="border-b-2 border-primary pb-2 font-medium text-primary">Board</span><span className="pb-2 text-muted-foreground">List</span><span className="pb-2 text-muted-foreground">Analytics</span><span className="ml-auto flex items-center gap-1 pb-2 text-muted-foreground"><LayoutGrid className="size-3" /><List className="size-3" /></span></div>
      <div className="grid grid-cols-3 gap-2 sm:gap-3">{columns.map(column => <div key={column.label} className="min-w-0 rounded-md bg-canvas p-2"><div className="mb-3 flex items-center gap-1.5 text-[10px] font-medium"><span className={cn('size-1.5 shrink-0 rounded-full', column.color)} /><span>{column.label}</span><span className="ml-auto text-muted-foreground">2</span></div><div className="flex flex-col gap-2">{column.tasks.map(task => <div key={task.key} className="rounded-md border bg-surface p-2.5 shadow-sm"><div className="flex items-center justify-between text-[9px] text-muted-foreground"><span>{task.key}</span><MoreHorizontal className="size-3" /></div><p className="mt-2 min-h-9 text-[11px] font-medium leading-[1.45] text-strong">{task.title}</p><span className={cn('mt-2 inline-flex items-center gap-1 text-[9px]', task.priority === 'Urgent' ? 'text-danger' : task.priority === 'High' ? 'text-avatar-amber' : 'text-muted-foreground')}><Circle className="size-1.5 fill-current" />{task.priority}</span><div className="mt-2 flex items-center gap-1 text-[9px] text-muted-foreground">{column.label === 'Done' ? <Check className="size-3 text-success" /> : <CalendarDays className="size-3" />}{task.date}</div><div className="mt-3 flex items-center justify-between border-t pt-2"><span className="flex size-5 items-center justify-center rounded-full bg-brand-50 text-[8px] font-medium text-primary">{task.initials}</span><span className="flex items-center gap-1 text-[9px] text-muted-foreground"><MessageSquare className="size-3" />{task.comments}</span></div></div>)}</div><div className="mt-3 flex items-center gap-1 text-[9px] text-muted-foreground"><Plus className="size-3" />Add task</div></div>)}</div>
    </div>
    <figcaption className="flex items-center justify-between border-t bg-brand-50 px-4 py-2 text-[10px] text-primary"><span className="flex items-center gap-1.5"><Check className="size-3" />Everyone on the same page.</span><span>Illustrative preview</span></figcaption>
  </figure>
}
